# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f44925cd9661397b3fbede78718759559483e7a4eab85a1f9f6b9c62bef9f48928a7260e963e8107405e1b81742926f1dde86b8689b8f76503db6b736ddfc998

test:
  secret_key_base: ec34ebbcd69b40cf8b7022ac355e038b15d44b3623926e4a1feadb4bbb83c412c1729ae36cce840b8306291a1e8dec91f06cc819226611577541ddf15e5d674d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
